"""
make_eco.py — конвертира eco_openings.tsv -> eco.h

Same model as make_book.py: a generated C header compiled straight into the
program (book.h already works that way). Data is lichess-org/chess-openings,
the same public-domain set the Qt build of Ferz uses.

Пусни:  python make_eco.py
Резултат: eco.h  (в същата папка)
"""
import os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
TSV  = os.path.join(HERE, "eco_openings.tsv")
OUT  = os.path.join(HERE, "eco.h")

def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')

if not os.path.exists(TSV):
    print(f"Файлът не е намерен: {TSV}")
    sys.exit(1)

rows = []
seen = set()
with open(TSV, "r", encoding="utf-8") as f:
    for line in f:
        line = line.rstrip("\n").rstrip("\r")
        if not line.strip():
            continue
        parts = line.split("\t")
        if len(parts) < 3:
            continue
        eco, name, moves = parts[0].strip(), parts[1].strip(), parts[2].strip()
        if not eco or not moves:
            continue
        toks = moves.split()
        if not toks:
            continue
        key = " ".join(toks)
        if key in seen:          # една и съща линия с друго име -> първата печели
            continue
        seen.add(key)
        rows.append((eco, name, " ".join(toks)))

# No sorting needed: the C side picks the DEEPEST line that is fully matched, and
# ties cannot happen (identical move strings were de-duplicated above).

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("/* Auto-generated by make_eco.py from eco_openings.tsv")
    f.write(" (lichess-org/chess-openings) - do not edit by hand */\n")
    f.write("#ifndef ECO_H\n#define ECO_H\n\n")
    f.write("typedef struct { const char *eco; const char *name; const char *moves; } EcoLine;\n\n")
    f.write(f"#define ECO_LINES_N {len(rows)}\n\n")
    f.write("static const EcoLine eco_lines[] = {\n")
    for eco, name, moves in rows:
        f.write('  {"%s","%s","%s"},\n' % (c_escape(eco), c_escape(name), c_escape(moves)))
    f.write("};\n\n#endif\n")

print(f"{len(rows)} ECO линии -> {OUT}")
print(f"размер: {os.path.getsize(OUT)} байта")



